apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: t597b5g2u-go-gitops
  description: This is GitOps manifest for t597b5g2u-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=t597b5g2u-go
    backstage.io/kubernetes-id: t597b5g2u-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: t597b5g2u-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:t597b5g2u-go
